/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CourierGUI1.java
 *
 * Created on Sep 18, 2009, 6:23:37 PM
 */

package com.duc.Reception;
import com.duc.ImportSection.MapForIndex;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.MessageFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable.PrintMode;
import javax.swing.table.DefaultTableModel;
import static com.duc.DatabaseConnection.DatabaseConnection.*;
/**
 *
 * @author Ravi Dangaich
 */
public class Courier extends javax.swing.JInternalFrame {
DefaultTableModel dm;
//DateFormat df;
//MapForIndex mp=new MapForIndex();
         HashMap classmap=mp.getClassIndexName();
         HashMap classmap1=mp.getClassIndexFromName();
    /** Creates new form CourierGUI1 */
    public Courier()  {
        initComponents();
        pack();
        //this.setLocationRelativeTo(null);
       //this.setLocation(100, 0);
        dm = (DefaultTableModel) jTable1.getModel();
        dm.setRowCount(1);
       // df=new SimpleDateFormat("yyyy-MM-dd");
         dateofcourier.setDateFormat(df);
         dateofcourier1.setDateFormat(df);
         fromClass();

          allCourier();
    }


    public void fromClass()
    {
         try
    {

// con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();


         ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();


            while (rs.next())
            {
        classcombo.addItem(rs.getString(1));


            }

 // con.close();
         }
    catch(Exception e)
    {
        System.err.println("Error is"+e);
    }

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        printButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        showAllCourierButton = new javax.swing.JButton();
        personname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        classcombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        dateofcourier = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        dateWiseSearchButton = new javax.swing.JButton();
        newCourierButton = new javax.swing.JButton();
        groupcombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        couriername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateofcourier1 = new datechooser.beans.DateChooserCombo();

        setClosable(true);
        setIconifiable(true);
        setTitle("Courier Services");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S. No.", "Name Of Person", "Sender", "CourierObject", "Class", "Ph. No.", "Remarks", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jTextPane1.setText("                                        Courier Register");
        jScrollPane2.setViewportView(jTextPane1);

        jTextPane2.setBackground(new java.awt.Color(204, 204, 255));
        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextPane2.setText("It will help you to manage all the couries relating to teachers or students specifically, in your institute...");
        jScrollPane3.setViewportView(jTextPane2);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        showAllCourierButton.setText("Show All");
        showAllCourierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllCourierButtonActionPerformed(evt);
            }
        });

        personname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                personnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                personnameKeyTyped(evt);
            }
        });

        jLabel1.setText("Name Wise Search");

        classcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "choose" }));
        classcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classcomboActionPerformed(evt);
            }
        });

        jLabel2.setText("Class");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Date From");

        dateWiseSearchButton.setText("Search");
        dateWiseSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateWiseSearchButtonActionPerformed(evt);
            }
        });

        newCourierButton.setText("New Courier");
        newCourierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourierButtonActionPerformed(evt);
            }
        });

        groupcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "choose", "Student", "Teacher" }));
        groupcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupcomboActionPerformed(evt);
            }
        });

        jLabel3.setText("Group");

        jLabel4.setText("Courier Wise Search");

        couriername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                couriernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                couriernameKeyTyped(evt);
            }
        });

        jLabel7.setText("Date To");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showAllCourierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCourierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(couriername, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateofcourier1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(personname, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE))
                            .addComponent(groupcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateofcourier, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(dateWiseSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(personname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(classcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(groupcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(dateofcourier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(couriername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateWiseSearchButton)
                            .addComponent(dateofcourier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newCourierButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showAllCourierButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try
        {
        String s="Student Courier Result";
        MessageFormat header=new MessageFormat(s);
        jTable1.print(PrintMode.FIT_WIDTH, header, null);
        }

        catch(Exception e)
        {
         System.err.println("Error in printing courier");
        }
}//GEN-LAST:event_printButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();            // TODO add your handling code here:
}//GEN-LAST:event_closeButtonActionPerformed

    private void showAllCourierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllCourierButtonActionPerformed
        allCourier();     //   showAllDefaultersList();        // TODO add your handling code here:
}//GEN-LAST:event_showAllCourierButtonActionPerformed

    private void personnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personnameKeyPressed
        //  if(!studentname.getText().isEmpty())viewDefaultersList();     // TODO add your handling code here:
}//GEN-LAST:event_personnameKeyPressed

    private void personnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personnameKeyTyped
        int keycode=evt.getID();
        int id;
        if(keycode==KeyEvent.KEY_TYPED) {

            CourierDetailOnBasisOfName();
            // id=Integer.parseInt(jTextField1.getText());
            // loadAdmissionNoTable(id);

        }
}//GEN-LAST:event_personnameKeyTyped

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!groupcombo.getSelectedItem().equals("choose"))
        saveCourier();
        else
            JOptionPane.showConfirmDialog(null,"Select group","group selection",JOptionPane.OK_OPTION);// TODO add your handling code here:
}//GEN-LAST:event_saveButtonActionPerformed

    private void dateWiseSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateWiseSearchButtonActionPerformed
        viewCourierByDate();    // TODO add your handling code here:
}//GEN-LAST:event_dateWiseSearchButtonActionPerformed

    private void newCourierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourierButtonActionPerformed
        reset();    // TODO add your handling code here:
}//GEN-LAST:event_newCourierButtonActionPerformed

    private void couriernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_couriernameKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_couriernameKeyPressed

    private void couriernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_couriernameKeyTyped
        int keycode=evt.getID();
        int id;
        if(keycode==KeyEvent.KEY_TYPED) {

            CourierDetailOnBasisOfCourierName();
            // id=Integer.parseInt(jTextField1.getText());
            // loadAdmissionNoTable(id);

        }
}//GEN-LAST:event_couriernameKeyTyped

    private void groupcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupcomboActionPerformed
        courierByGroup();
    }//GEN-LAST:event_groupcomboActionPerformed

    private void classcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classcomboActionPerformed
        // viewCourierByClass();
        dm.setValueAt(classcombo.getSelectedItem().toString(), 0, 4);
    }//GEN-LAST:event_classcomboActionPerformed

 public void reset()
    {
        dm.setRowCount(1);
        dm.setValueAt("", 0, 0);
                dm.setValueAt("", 0, 1);
                 dm.setValueAt("", 0, 2);
                 dm.setValueAt("", 0, 3);
                dm.setValueAt("", 0, 4);
                 dm.setValueAt("", 0, 5);
                  dm.setValueAt("", 0, 6);
                 dm.setValueAt("", 0, 7);
    }

        public void allCourier()
  {
      //con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();

     try
     {
       ps=con.prepareStatement("select * from courier order by serial") ;

       rs=ps.executeQuery();
      populateTable(rs);

  //con.close();
     }catch(Exception e)
   {
e.printStackTrace();
   }
  }

         public void courierByGroup()
    {
        int i=0,j=0;
   // con=new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
    try
    {
        ps=con.prepareStatement("select * from courier where category=? order by serial");
        ps.setString(1,groupcombo.getSelectedItem().toString());

        rs=ps.executeQuery();
       // System.out.println("value"+rs.next());
        populateTable(rs);
 //System.out.println(rs.getString(9));
  //  con.close();
    }catch(Exception e)
    {
e.printStackTrace();
    }
    }

        public void viewCourierByClass()
    {
        int i=0,j=0;
   //con=new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
    try
    {
        ps=con.prepareStatement("select * from courier where class=? order by serial");
        ps.setInt(1,Integer.parseInt(classmap1.get(classcombo.getSelectedItem().toString()).toString()));

        rs=ps.executeQuery();
       // System.out.println("value"+rs.next());
        populateTable(rs);
 //System.out.println(rs.getString(9));
    //con.close();
    }catch(Exception e)
    {
e.printStackTrace();
    }
    }

public void viewCourierByDate()
    {
        int i=0,j=0;
   // con=new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
    try
    {
        ps=con.prepareStatement("select * from courier where dat>=? and dat<=? order by serial");
         ps.setString(1,dateofcourier.getText());
ps.setString(2,dateofcourier1.getText());
        rs=ps.executeQuery();
       // System.out.println("value"+rs.next());
        populateTable(rs);
 //System.out.println(rs.getString(9));
   // con.close();
    }catch(Exception e)
    {
e.printStackTrace();
    }
    }
        public void saveCourier()
{
    // con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();

            try
            {
   ps=con.prepareStatement("insert into courier(category,personname,sendername,courierobject,class,ph,remarks,dat) values(?,?,?,?,?,?,?,?)");

                ps.setString(1,groupcombo.getSelectedItem().toString());//group
                ps.setString(2,dm.getValueAt(0,1).toString());//personname
                 ps.setString(3,dm.getValueAt(0,2).toString());//sendername
                ps.setString(4,dm.getValueAt(0,3).toString());
                ps.setInt(5,Integer.parseInt(classmap1.get(dm.getValueAt(0,4).toString()).toString()));//class

              ps.setString(6,dm.getValueAt(0,5).toString());//ph

                 ps.setString(7,dm.getValueAt(0,6).toString());//remarks
 //ps.setString(7,dm.getValueAt(0,6).toString());
                 ps.setString(8,datum);

                ps.executeUpdate();
         // con.close();
            }

            catch(Exception e)
            {
e.printStackTrace();
            }
}

        public void CourierDetailOnBasisOfName()
{
    // con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();


         int i=0,j=0;

     try
     {
       ps=con.prepareStatement("select * from courier where personname like ? order by serial") ;
      ps.setString(1,personname.getText()+"%");
         //ps.setInt(2,id);
      System.out.println("n");
       rs=ps.executeQuery();
      populateTable(rs);

 //  con.close();
     }catch(Exception e)
   {
e.printStackTrace();
   }
}
public void CourierDetailOnBasisOfCourierName()
{
    // con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();


         int i=0,j=0;

     try
     {
       ps=con.prepareStatement("select * from courier where courierobject like ? order by serial") ;
      ps.setString(1,couriername.getText()+"%");
         //ps.setInt(2,id);
      System.out.println("n");
       rs=ps.executeQuery();
      populateTable(rs);

  // con.close();
     }catch(Exception e)
   {
e.printStackTrace();
   }
}
public void populateTable(ResultSet rs)
    {
        int i=0,j=0;
        try
        {
            while(rs.next())
            {
                j++;
               // System.out.println("gender"+rs);
              //  System.out.println("rd2");
            }
            rs.first();
            rs.previous();
            System.out.println(dateofcourier.getText());
            dm.setRowCount(j);
            System.out.println(j);
            //rs.next();
            while(rs.next())
            {
            dm.setValueAt(rs.getInt(1), i, 0);
                dm.setValueAt(rs.getString(3), i, 1);
                 dm.setValueAt(rs.getString(4), i, 2);
                 dm.setValueAt(rs.getString(5), i, 3);
                dm.setValueAt(classmap.get(rs.getInt(6)), i, 4);
               dm.setValueAt(rs.getString(7), i, 5);
                 dm.setValueAt(rs.getString(8), i, 6);
                  dm.setValueAt(rs.getString(9), i, 7);


                 i++;
        }
    }catch(Exception e)
    {
e.printStackTrace();
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox classcombo;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField couriername;
    private javax.swing.JButton dateWiseSearchButton;
    private datechooser.beans.DateChooserCombo dateofcourier;
    private datechooser.beans.DateChooserCombo dateofcourier1;
    private javax.swing.JComboBox groupcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton newCourierButton;
    private javax.swing.JTextField personname;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton showAllCourierButton;
    // End of variables declaration//GEN-END:variables
//Connection con;
ResultSet rs;
PreparedStatement ps;
}
