/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TodayReplacementList.java
 *
 * Created on Jan 7, 2010, 9:04:26 PM
 */

package com.duc.SpecialDepartment.TimeTableSection;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import java.sql.*;
//import java.util.ArrayList;
//import javax.swing.JOptionPane;
import javax.swing.JTable.PrintMode;
//import java.text.MessageFormat;
//import java.util.HashMap;
import com.duc.ImportSection.MapForIndex;
import static com.duc.DatabaseConnection.DatabaseConnection.*;
import java.util.*;
import java.text.*;


/**
 *
 * @author sourabh
 */
public class TodayReplacementList extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
   // MapForIndex mp=new MapForIndex();
    HashMap classmap=mp.getClassIndexName();
   // HashMap subjectmap=mp.getSubjectIndexToName();
    HashMap sectionmap=mp.getSectionIndexName();
    HashMap allTeachers=new HashMap();
    ArrayList<String> absents= new ArrayList<String>();
    
    /** Creates new form TodayReplacementList */
    public TodayReplacementList() {
        initComponents();
        jXTable1.setHorizontalScrollEnabled(true);
        jXTable1.setHighlighters(HighlighterFactory.createAlternateStriping());
        model = new TimeTableModel(1).createDefaultModel();
        jXTable1.setModel(model);
        addTeachers();
        loadAbsents();
        model.setRowCount(absents.size());
        loadReplacements();
    }

    public void loadReplacements()
    {
      try
      {
        String tabsent="" ,t="" ;
         for(int i=0;i<absents.size();i++)
       {
          tabsent=absents.get(i);
          System.out.println(tabsent);
          ps=con.prepareStatement("select col,t_replace,class,section from teacher_replacement where t_absent=? and date=(select current_date())");
          ps.setString(1,tabsent);
          rs=ps.executeQuery();
          model.setValueAt(allTeachers.get(tabsent).toString()+" ["+tabsent +" ]", i, 0);
          
          while(rs.next())
          {
          System.out.println("Processing "+ tabsent);
          t="<html>"+allTeachers.get(rs.getString(2)).toString()+"<br />"+classmap.get(rs.getInt(3)).toString()+"-"+sectionmap.get(rs.getInt(4)).toString() +"</html>";
          model.setValueAt(t, i, rs.getInt(1));
          }
        }
      }
      catch(Exception e)
      {
        e.printStackTrace();
      }
    }

    public void loadAbsents()
    {
      
       try
       {
         ps=con.prepareStatement("select distinct t_absent from teacher_replacement where date=current_date() ");
         rs=ps.executeQuery();
         while(rs.next())
         {
         absents.add(rs.getString(1));
         }
       }
       catch(Exception e)
       {
        e.printStackTrace();
       }

    }
    
     public void addTeachers()
    {
       allTeachers.clear();
       try
       {
         ps=con.prepareStatement("select distinct teachercode,name from subjectallotment,staffentry where teachercode=code ");
         rs=ps.executeQuery();
         while(rs.next())
         {
         allTeachers.put(rs.getString(1), rs.getString(2));
         System.out.println(rs.getString(1)+ ":" +rs.getString(2));
         }
       }
       catch(Exception e)
       {
        e.printStackTrace();
       }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);
        setTitle("Absent Teacher's Adjustments");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1.setColumnControlVisible(true);
        jXTable1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jXTable1.setHorizontalScrollEnabled(true);
        jXTable1.setRowHeight(90);
        jScrollPane2.setViewportView(jXTable1);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextPane1.setText("                                                                           Adjustment List for absent teachers");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
         java.util.Date today=new java.util.Date();
         String dateOut;
         DateFormat dateFormatter;

         dateFormatter =
         DateFormat.getDateInstance();
         dateOut = dateFormatter.format(today);

        String s="List of Adjustments for absent teachers: ";
        s+=dateOut;
        MessageFormat header=new MessageFormat(s);
        jXTable1.print(PrintMode.FIT_WIDTH, header, null);
        }
        catch(Exception e)
        {
         System.err.println("Error in printing timetable");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int i=jXTable1.getRowHeight();
        jXTable1.setRowHeight(i+5);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int i=jXTable1.getRowHeight();
        if(i>30)
            jXTable1.setRowHeight(i-5);
}//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
   PreparedStatement ps;
   ResultSet rs;
}
