/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransportBoardersList.java
 *
 * Created on Nov 16, 2009, 12:48:01 AM
 */

package com.duc.SpecialDepartment.MoreSection.TransportSection;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import java.sql.*;
import java.text.MessageFormat;
import java.util.HashMap;
import javax.swing.JTable.PrintMode;
import javax.swing.table.DefaultTableModel;
import static com.duc.DatabaseConnection.DatabaseConnection.*;
/**
 *
 * @author Ravi
 */
public class TransportBoardersList extends javax.swing.JInternalFrame {
DefaultTableModel dm;
HashMap classmap=mp.getClassIndexName();
    /** Creates new form TransportBoardersList */
    public TransportBoardersList() {
        initComponents();
         pack();
         jTable1.setHighlighters(HighlighterFactory.createAlternateStriping());
        jTable1.setHorizontalScrollEnabled(true);
        dm = (DefaultTableModel) jTable1.getModel();
        dm.setRowCount(0);
        fromTransportBoarders();
        totalStrength();
    }

    public void fromTransportBoarders()
    {
         int j=0,i=0;
         int feeid=0;
         //con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
         try
         {
             ps=con.prepareStatement("select * from monthlyfeehead where head='Transport Fee'");
             rs=ps.executeQuery();
             if(rs.next())
                 feeid=rs.getInt(1);

             ps=con.prepareStatement("select * from transportboarders left join studententry on studentid=id where status=1");
             rs=ps.executeQuery();
             if(rs.next())
             {
                 rs.first();
                 rs.previous();
             while(rs.next())
             {
                 j++;
             }
             dm.setRowCount(j);
             rs.first();
             rs.previous();
             while(rs.next())
             {
                dm.setValueAt(rs.getString(1), i, 0);
                //dm.setValueAt(rs.getString(1), i, 0);
               //-- ps=con.prepareStatement("select * from studententry where id=?");
               //-- ps.setString(1,rs.getString(1));
             //--rs1=ps.executeQuery();
            //-- while(rs1.next())
             //--{
                 dm.setValueAt(rs.getString(8), i, 2);
                 dm.setValueAt(classmap.get(rs.getInt(15)),i,1);
                 //System.out.println("fdfdfs"+String.valueOf(rs1.getInt(9)));
             //--}
             //System.out.println("fdfdfs"+classmap.get(rs1.getInt(2)).toString());

             dm.setValueAt(rs.getString(2), i, 3);
             dm.setValueAt(rs.getString(3), i, 4);

             dm.setValueAt(rs.getString(4), i, 5);
             dm.setValueAt(rs.getString(5), i, 6);

             ps=con.prepareStatement("select amount from feecustomization where studentid=? and head=? and feeheadtype=0");
             ps.setString(1,rs.getString(1));
             ps.setInt(2,feeid);
             rs1=ps.executeQuery();

             if(rs1.next())
             {
                 dm.setValueAt(rs1.getDouble(1), i, 7);
             }
             else
                 dm.setValueAt(0.0, i, 7);

             dm.setValueAt(rs.getString(6), i, 8);
             i++;
             }
             }
         }catch(Exception e)
         {
             e.printStackTrace();
         }

    }

      public void totalStrength()
    {
        Double total=0.0;
        for(int i=0;i<dm.getRowCount();i++)
            total+=Double.parseDouble(dm.getValueAt(i,7).toString());
        totalstrength.setText(String.valueOf(dm.getRowCount()));
        System.out.println("fffffffffff"+total);

        int rowcount=dm.getRowCount();
     System.out.println("row"+rowcount);
    dm.setRowCount(rowcount+1);

    dm.setValueAt("Total Fee", rowcount, 0);
    dm.setValueAt(total, rowcount, 7);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();
        totalstrength = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Boarders List");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTextPane1.setText("                                       Transport Boarders List");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane2.setEditable(false);
        jTextPane2.setText("List of students who are availing the transport facility of the Institute..");
        jScrollPane2.setViewportView(jTextPane2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Studentid", "Class", "Name", "Stop Name", "Route No.", "Bus No.", "Pick & Drop", "Fee", "DOA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setText("Total No. Of Students");

        totalstrength.setText("jLabel2");

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(totalstrength, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalstrength)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String s="Transport Boarders List";
            MessageFormat header=new MessageFormat(s);
            jTable1.print(PrintMode.FIT_WIDTH, header, null);
        }catch(Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel totalstrength;
    // End of variables declaration//GEN-END:variables
ResultSet rs,rs1;
//Connection con;
PreparedStatement ps;
}
