/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchoolExpenditure1.java
 *
 * Created on Sep 22, 2009, 4:26:05 PM
 */

package com.duc.SpecialDepartment.AccountSection;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import static com.duc.DatabaseConnection.DatabaseConnection.*;
/**
 *
 * @author Ravi Dangaich
 */
public class SchoolExpenditure extends javax.swing.JInternalFrame {
DefaultTableModel dm;

    /** Creates new form SchoolExpenditure1 */
    public SchoolExpenditure() {
        initComponents();
        pack();
        //this.setLocationRelativeTo(null);
        //setLocation(150,50);
        dm = (DefaultTableModel)jTable1.getModel();
        dm.setRowCount(0);
       
        showAddedProduct();
    }

    public void deductFromRespectiveLedger()
    {
int ledcode=0;
    double netbalance=0.0;
   // con=new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
    try
    {
      ps=con.prepareStatement("Select * from ledgerotherfeeheadcode where feehead=?");
         ps.setString(1,"School Expenditure");
         rs=ps.executeQuery();
        // System.out.println("FFFFFFFFFFFFFFFFFF");
         if(rs.next())
         ledcode=rs.getInt(2);
ps=con.prepareStatement("select * from schoolexpenditure where serial=?");
         ps=con.prepareStatement("select * from ledgeraccount where ledgercode=?");
             ps.setInt(1,ledcode);
             rs=ps.executeQuery();
             while(rs.next())
             {
                 netbalance=rs.getDouble(3)-Double.parseDouble(amountgiven.getText());

                 ps=con.prepareStatement("update ledgeraccount set paid=? where ledgercode=?");
                 ps.setDouble(1, netbalance);
                 ps.setInt(2,ledcode);
                 ps.executeUpdate();
             }
                 ps=con.prepareStatement("insert into ledgercreditdebitrecord (ledgercode,transactiontype,head,subhead,amount,date) values(?,?,?,?,?,?)");
    ps.setInt(1,ledcode);
    ps.setString(2,"Cr.");
    ps.setString(3,"School Expenditure");
    ps.setString(4,"Product="+itemname.getText());
    ps.setDouble(5, Double.parseDouble(amountgiven.getText()));
    ps.setString(6,datum);
    ps.executeUpdate();

    }catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        remarks = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel31 = new javax.swing.JLabel();
        admissionfeecheckbox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        orderdby = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        receivedby = new javax.swing.JTextField();
        amountgiven = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        amountreturned = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        issuedon = new javax.swing.JTextField();
        updateon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        expkey = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Institute Expenditure ");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTextPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextPane2.setText("                                  Institute Expenditure"); // NOI18N
        jTextPane2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextPane2);

        jLabel10.setText("List of Items Used by Institute"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("Remarks"); // NOI18N

        remarks.setColumns(20);
        remarks.setRows(5);
        jScrollPane5.setViewportView(remarks);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "              Item List", "Exp. Key"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jButton1.setText("ADD"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Show Items"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Item"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane3.setEditable(false);
        jTextPane3.setText("Maintain the products records  used in your school."); // NOI18N
        jScrollPane3.setViewportView(jTextPane3);

        jLabel31.setText("Set Ledger"); // NOI18N

        admissionfeecheckbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionfeecheckbox2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Product Name"); // NOI18N

        itemname.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Ordered By"); // NOI18N

        jLabel4.setText("Received By"); // NOI18N

        amountgiven.setText("0");

        jLabel6.setText("Amount Given"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(itemname, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountgiven, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receivedby, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(orderdby))))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(orderdby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(receivedby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountgiven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setText("Amount Returned"); // NOI18N

        amountreturned.setText("0");

        jLabel2.setText("Issued On"); // NOI18N

        issuedon.setBackground(new java.awt.Color(153, 153, 153));
        issuedon.setEditable(false);

        updateon.setBackground(new java.awt.Color(153, 153, 153));
        updateon.setEditable(false);

        jLabel13.setText("Last Update"); // NOI18N

        jLabel7.setText("Exp. Key"); // NOI18N

        expkey.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expkey, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(updateon, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(issuedon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(112, 112, 112))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(amountreturned, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuedon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(updateon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(expkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(amountreturned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(114, 114, 114)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addGap(110, 110, 110)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(admissionfeecheckbox2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(118, 118, 118)))
                        .addGap(227, 227, 227))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(jLabel31)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(admissionfeecheckbox2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // com.duc.FeeDepartment.LedgerSection.Setup.LedgerOtherFeeHeadSetup r=new com.duc.FeeDepartment.LedgerSection.Setup.LedgerOtherFeeHeadSetup();

        //r.setVisible(true);
       // this.add(r,0);
        //r.setReference(this);
        /*click++;
        if(click==1)
        {
        showOtherFeeHeadCode();
        }*/
        try
        {
        ps=con.prepareStatement("select * from ledgerotherfeeheadcode where feehead=?");
            ps.setString(1,"School Expenditure");
            rs=ps.executeQuery();
            if(!rs.next())
            {
                 ps=con.prepareStatement("insert into ledgerotherfeeheadcode (feehead) values(?)");
                ps.setString(1,"School Expenditure");
                ps.executeUpdate();
            }
       // else
        {
        addProduct();
        deductFromRespectiveLedger();
        }// TODO add your handling code here:
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(itemname.getText().isEmpty())
            JOptionPane.showConfirmDialog(null,"No Product for Update","Product Blanck Alarm",JOptionPane.OK_CANCEL_OPTION);
        else
        {
           updateLedgerProductRecord();
            updateProductRecord();

             
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showAddedProduct();        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        deleteProduct();        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
showProductDetail();        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void admissionfeecheckbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionfeecheckbox2ActionPerformed

        showOtherFeeHeadCode();
}//GEN-LAST:event_admissionfeecheckbox2ActionPerformed

    public void showOtherFeeHeadCode()
    {
        com.duc.FeeDepartment.LedgerSection.Setup.LedgerOtherFeeHeadSetup r=new com.duc.FeeDepartment.LedgerSection.Setup.LedgerOtherFeeHeadSetup();

        r.setVisible(true);
        r.setReference("School Expenditure");
        this.add(r,0);
    }

    public void updateLedgerProductRecord()
    {
int ledcode=0;
    double netbalance=0.0;
    currentrow=jTable1.getSelectedRow();

String productname=jTable1.getValueAt(currentrow,0).toString();
int key=Integer.parseInt(jTable1.getValueAt(currentrow,1).toString());
Double earliervalue=0.0;
  //  con=new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
    try
    {
      ps=con.prepareStatement("Select * from ledgerotherfeeheadcode where feehead=?");
         ps.setString(1,"School Expenditure");
         rs=ps.executeQuery();
        // System.out.println("FFFFFFFFFFFFFFFFFF");
         if(rs.next())
         ledcode=rs.getInt(2);
ps=con.prepareStatement("select * from schoolexpenditure where serialnumber=?");
ps.setInt(1,Integer.parseInt(expkey.getText()));
rs=ps.executeQuery();
if(rs.next())
    earliervalue=rs.getDouble(5);
         ps=con.prepareStatement("select * from ledgeraccount where ledgercode=?");
             ps.setInt(1,ledcode);
             rs=ps.executeQuery();
             while(rs.next())
             {
                 netbalance=rs.getDouble(3)+ earliervalue-Double.parseDouble(amountgiven.getText())+Double.parseDouble(amountreturned.getText());

                 ps=con.prepareStatement("update ledgeraccount set paid=? where ledgercode=?");
                 ps.setDouble(1, netbalance);
                 ps.setInt(2,ledcode);
                 ps.executeUpdate();
             }
                 //Double.parseDouble(amountgiven.getText())

    }catch(Exception e)
    {
        e.printStackTrace();
    }
    }

    public void updateProductRecord()
    {
      itemname.setEditable(false);
//con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
try
{
    ps=con.prepareStatement("update schoolexpenditure set orderby=?,processby=?,amountgiven=?,amountreturned=?,remarks=?,updateon=? where itemname=?");
   
    ps.setString(1, orderdby.getText());
    ps.setString(2,receivedby.getText());

    ps.setDouble(3,Double.parseDouble(amountgiven.getText()));
 ps.setDouble(4,Double.parseDouble(amountreturned.getText()));

    ps.setString(5, remarks.getText());
     ps.setString(6,datum);
    ps.setString(7,itemname.getText());
    ps.executeUpdate();
    System.out.println("data updated");

}catch(Exception e)
{
e.printStackTrace();
}

    }
 public void showProductDetail()
    {
        currentrow=jTable1.getSelectedRow();

String productname=jTable1.getValueAt(currentrow,0).toString();
int key=Integer.parseInt(jTable1.getValueAt(currentrow,1).toString());
//con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
try
{
    ps=con.prepareStatement("Select * from schoolexpenditure where itemname=? and serialnumber=?");
  ps.setString(1,productname);
  ps.setInt(2, key);
   rs= ps.executeQuery();
   rs.next();
    System.out.println("Now set the data to each field");
    itemname.setText(rs.getString(2));
    
    orderdby.setText(rs.getString(3));
    receivedby.setText(rs.getString(4));

    amountgiven.setText(String.valueOf(rs.getDouble(5)));
 amountreturned.setText(String.valueOf(rs.getDouble(6)));
    remarks.setText(rs.getString(7));
    issuedon.setText(rs.getString(8));
    updateon.setText(rs.getString(9));
expkey.setText(String.valueOf(rs.getInt(1)));

}catch(Exception e)
{
e.printStackTrace();
}

    }
    public void deleteProduct()
    {
        // con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
        int row = jTable1.getSelectedRow();
         System.out.println("row no. selected"+row);
        try
        {
         ps=con.prepareStatement("delete from schoolexpenditure where itemname=?");

         ps.setString(1,dm.getValueAt(row, 0).toString());
         ps.executeUpdate();
         dm.removeRow(row);
         // con.close();
         System.out.println("DataBase Conection Closed");
    }
        catch(Exception e)
        {
            System.err.println("Error"+e);
        }

    }

    public void addProduct()
    {
        if(itemname.getText().isEmpty())
            JOptionPane.showConfirmDialog(null,"No Product Filled","Product Blanck Alarm",JOptionPane.OK_CANCEL_OPTION);
    else
{
       // con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
 try
 {
     ps=con.prepareStatement("insert into schoolexpenditure(itemname,orderby,processby,amountgiven,amountreturned,remarks,date,updateon) values(?,?,?,?,?,?,?,?)");
 ps.setString(1,itemname.getText()); 
  ps.setString(2,orderdby.getText());
  ps.setString(3,receivedby.getText());

 ps.setDouble(4,Double.parseDouble(amountgiven.getText()));
 ps.setDouble(5,Double.parseDouble(amountreturned.getText()));
  ps.setString(6,remarks.getText());
  ps.setString(7,datum);
    ps.setString(8,datum);

  System.out.println("ff3");
            ps.executeUpdate();

  System.out.println("the product is entered into the database");
   //model.addElement(String.valueOf(jTextField1.getText()));

 }catch(Exception e)
 {
     e.printStackTrace();
 }

    }

   showAddedProduct();


    }

    public void showAddedProduct()
    {


    // con= new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
       try
       {
           ps = con.prepareStatement("select * from schoolexpenditure");
System.out.println("done2");
           rs = ps.executeQuery();
           System.out.println("done3");
            int i = 0,j=0;
          while(rs.next() )
            {
                j++;System.out.println("done5");
            }
            rs.first();
            System.out.println("done6");
            rs.previous();
            System.out.println("done7");
            dm.setRowCount(j);
            while(rs.next())
            {
                dm.setValueAt(rs.getString(2), i, 0);
                //System.out.println("done6");
                dm.setValueAt(rs.getInt(1), i, 1);

                i++;
            }
          //  con.close();
            System.out.println("Database closed");

       }
       catch(Exception e)
       {
          e.printStackTrace();
       }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox admissionfeecheckbox2;
    private javax.swing.JTextField amountgiven;
    private javax.swing.JTextField amountreturned;
    private javax.swing.JTextField expkey;
    private javax.swing.JTextField issuedon;
    private javax.swing.JTextField itemname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField orderdby;
    private javax.swing.JTextField receivedby;
    private javax.swing.JTextArea remarks;
    private javax.swing.JTextField updateon;
    // End of variables declaration//GEN-END:variables
//Connection con;
ResultSet rs;
 PreparedStatement ps;
 int currentrow=0;
 public static int click=0;
}
