/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Graphs.java
 *
 * Created on Sep 5, 2010, 12:39:49 AM
 */

package com.duc.Accessories;
import com.lowagie.text.Document;
import com.lowagie.text.pdf.DefaultFontMapper;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import java.util.ArrayList;
import java.util.HashMap;
import org.jfree.chart.axis.CategoryLabelPositions;

import static com.duc.DatabaseConnection.DatabaseConnection.*;

/**
 *
 * @author ravi
 */
public class Graphs extends javax.swing.JInternalFrame {

    HashMap classmap1=mp.getClassIndexFromName();
         HashMap classmap=mp.getClassIndexName();
         HashMap sessionmap1=mp.getSessionIndexFromName();
          HashMap sessionmap=mp.getSessionIndexToName();

          HashMap religionmap1=mp.getReligionIndexFromName();
          HashMap religionmap=mp.getReligionNameFromIndex();

          HashMap categorymap=mp.getCategoryNameFromIndex();

          HashMap vendormap=mpi.getVendorNameIndexToName();
    /** Creates new form Graphs */
    public Graphs() {
        initComponents();
        fromSession();
        //Reception
        buttonGroup1.add(jRadioButton1);
           buttonGroup1.add(jRadioButton2);
    buttonGroup1.add(jRadioButton3);
    buttonGroup1.add(jRadioButton4);
    buttonGroup1.add(jRadioButton5);

    //Student
    buttonGroup1.add(jRadioButton6);
           buttonGroup1.add(jRadioButton7);
           buttonGroup1.add(jRadioButton13);
buttonGroup1.add(jRadioButton15);
buttonGroup1.add(jRadioButton16);
buttonGroup1.add(jRadioButton8);

    //Fee
   buttonGroup1.add(jRadioButton18);
   buttonGroup1.add(jRadioButton19);

   buttonGroup1.add(jRadioButton21);
           buttonGroup1.add(jRadioButton22);

           buttonGroup1.add(jRadioButton24);
   buttonGroup1.add(jRadioButton25);

   buttonGroup1.add(jRadioButton26);
           buttonGroup1.add(jRadioButton27);


           //Inventory
            buttonGroup1.add(jRadioButton52);
           buttonGroup1.add(jRadioButton53);
            buttonGroup1.add(jRadioButton58);
           buttonGroup1.add(jRadioButton59);

           //Transport
           buttonGroup1.add(jRadioButton88);
           buttonGroup1.add(jRadioButton89);

    }

    public void fromSession()
    {
         try
       {
           ps = con.prepareStatement("select sessiontitle,sessionid,status from sessionsetup ");

           rs = ps.executeQuery();
           // int i = 0,j=0;
          while(rs.next())
            {
                //j++;
             // sessionCombo.addItem(rs.getString(1));

              if(rs.getInt(3)==1)
                  sessionValue=rs.getInt(2);

            }



         }
         catch(Exception e)
         {
             e.printStackTrace();
    }
    }

        public static void writeChartToPDF(JFreeChart chart, int width, int height, String fileName)
 {
    PdfWriter writer = null;
    Document document = new Document();

    try {

        writer = PdfWriter.getInstance(document, new FileOutputStream(fileName));

        document.open();

        PdfContentByte contentByte = writer.getDirectContent();

        PdfTemplate template = contentByte.createTemplate(width, height);

        Graphics2D graphics2d = template.createGraphics(width, height, new DefaultFontMapper());

        Rectangle2D rectangle2d = new Rectangle2D.Double(0, 0, width,height);
        chart.draw(graphics2d, rectangle2d);
        graphics2d.dispose();

        contentByte.addTemplate(template, 0, 0);

    } catch (Exception e) {

        e.printStackTrace();
    }
    document.close();

}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jSeparator11 = new javax.swing.JSeparator();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton42 = new javax.swing.JRadioButton();
        jRadioButton112 = new javax.swing.JRadioButton();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton114 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jSeparator32 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jRadioButton79 = new javax.swing.JRadioButton();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jRadioButton81 = new javax.swing.JRadioButton();
        jSeparator41 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jRadioButton82 = new javax.swing.JRadioButton();
        jRadioButton83 = new javax.swing.JRadioButton();
        jSeparator42 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jRadioButton84 = new javax.swing.JRadioButton();
        jRadioButton85 = new javax.swing.JRadioButton();
        jRadioButton113 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jRadioButton88 = new javax.swing.JRadioButton();
        jSeparator44 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jRadioButton90 = new javax.swing.JRadioButton();
        jSeparator45 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        jRadioButton98 = new javax.swing.JRadioButton();
        jRadioButton99 = new javax.swing.JRadioButton();
        jRadioButton89 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);

        jTabbedPane1.setForeground(new java.awt.Color(153, 0, 51));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setText("Class Wise Enquiry Comparision");

        jRadioButton1.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton1.setText("Bar Chart");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton2.setText("Pie Chart");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("All Sessions-Class Wise Enquiry Comparision");

        jRadioButton3.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton3.setText("Bar Chart");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Area Wise Enquiry Comparision");

        jRadioButton4.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton4.setText("Bar Chart");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton5.setText("Pie Chart");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jRadioButton3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reception", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));

        jLabel4.setText("Class Wise Student Comparision");

        jRadioButton6.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton6.setText("Bar Chart");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton7.setText("Pie Chart");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Class-Category Comparision ");

        jRadioButton13.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton13.setText("Bar Chart");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jLabel9.setText("Class-Gender Comparision");

        jRadioButton15.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton15.setText("Bar Chart");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jLabel10.setText("Class-Religion Comparision");

        jRadioButton16.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton16.setText("Bar Chart");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jLabel5.setText("Session wise new Students Comparision");

        jRadioButton8.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton8.setText("Bar Chart");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton13)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jRadioButton6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton7)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addGap(5, 5, 5)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", jPanel3);

        jPanel11.setBackground(new java.awt.Color(0, 204, 153));

        jLabel11.setText("Class Wise Fee Dues Comparision");

        jRadioButton18.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton18.setText("Bar Chart");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jRadioButton19.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton19.setText("Pie Chart");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jLabel13.setText("Class Wise Fee Paid Comparision");

        jRadioButton21.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton21.setText("Pie Chart");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton22.setText("Bar Chart");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        jLabel15.setText("Class Wise Fine/Other Dues Comparision");

        jRadioButton24.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton24.setText("Bar Chart");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jRadioButton25.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton25.setText("Pie Chart");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        jLabel16.setText("Class Wise Fine/Other Paid Comparision");

        jRadioButton26.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton26.setText("Pie Chart");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        jRadioButton27.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton27.setText("Bar Chart");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jRadioButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton19)))
                        .addContainerGap(429, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(395, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jRadioButton22)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton21))
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                        .addGap(269, 269, 269))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jRadioButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton25))
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jRadioButton27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton26)))
                        .addContainerGap(395, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton26))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Fee     ", jPanel11);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));

        jLabel21.setText("A student, Exam-Grade Comparision");

        jRadioButton34.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton34.setText("Bar Chart");

        jRadioButton35.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton35.setText("Pie Chart");

        jLabel22.setText("For a Exam & Class, Subject-Grade Comparision");

        jRadioButton36.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton36.setText("Bar Chart");

        jRadioButton37.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton37.setText("Pie Chart");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton35))
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton37))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton37))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Exam   ", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));

        jLabel25.setText("A Student,Month Wise Attendance Comparision ");

        jRadioButton42.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton42.setText("Bar Chart");

        jRadioButton112.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton112.setText("Pie Chart");

        jLabel27.setText("A Staff,Month Wise Attendance Comparision");

        jRadioButton43.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton43.setText("Bar Chart");

        jRadioButton114.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton114.setText("Pie Chart");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton42)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton112))
                    .addComponent(jLabel25)
                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton43)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton114))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton42)
                    .addComponent(jRadioButton112))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton114))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Attendance", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 204, 153));

        jLabel31.setText("Class Wise Inventory Sold Comparision");

        jRadioButton52.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton52.setText("Bar Chart");
        jRadioButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton52ActionPerformed(evt);
            }
        });

        jRadioButton53.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton53.setText("Pie Chart");
        jRadioButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton53ActionPerformed(evt);
            }
        });

        jLabel35.setText("Vendor Wise Inventory Purchased Comparision");

        jRadioButton58.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton58.setText("Bar Chart");
        jRadioButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton58ActionPerformed(evt);
            }
        });

        jRadioButton59.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton59.setText("Pie Chart");
        jRadioButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton59ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRadioButton52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton53))
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRadioButton58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton59))
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton58)
                    .addComponent(jRadioButton59))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventory", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 204, 153));

        jLabel38.setText("Class Wise No. of Periods Comparision");

        jRadioButton64.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton64.setText("Bar Chart");

        jRadioButton65.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton65.setText("Pie Chart");

        jLabel42.setText("Teacher Wise No. of Periods Comparision");

        jRadioButton70.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton70.setText("Bar Chart");

        jRadioButton71.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton71.setText("Pie Chart");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jRadioButton64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton65))
                    .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jRadioButton70)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton71)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton64)
                    .addComponent(jRadioButton65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton70)
                    .addComponent(jRadioButton71))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Time-Table", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 204, 153));

        jLabel47.setText("Month Wise Books Circulation Comparision");

        jRadioButton79.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton79.setText("Bar Chart");

        jLabel48.setText("Month Wise Books Puchase requisition Comparision");

        jRadioButton81.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton81.setText("Bar Chart");

        jLabel49.setText("Publisher Wise No. of Books Comparision ");

        jRadioButton82.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton82.setText("Bar Chart");

        jRadioButton83.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton83.setText("Pie Chart");

        jLabel50.setText("Vendor Wise No. of Books Comparision");

        jRadioButton84.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton84.setText("Bar Chart");

        jRadioButton85.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton85.setText("Pie Chart");

        jRadioButton113.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton113.setText("Pie Chart");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton79)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jRadioButton81)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton113))
                    .addComponent(jSeparator41, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(jSeparator40, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jRadioButton82)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton83))
                            .addComponent(jSeparator42, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jRadioButton84)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton85)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel48))
                .addGap(219, 219, 219))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator40, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton81)
                    .addComponent(jRadioButton113))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator41, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton82)
                    .addComponent(jRadioButton83))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator42, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton84)
                    .addComponent(jRadioButton85))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Library ", jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 204, 153));

        jLabel52.setText("Bus Wise Capacity-Boarding Students Comparision");

        jRadioButton88.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton88.setText("Bar Chart");
        jRadioButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton88ActionPerformed(evt);
            }
        });

        jLabel53.setText("Area Wise Bus Boarder/Self-Vehicle Comparision ");

        jRadioButton90.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton90.setText("Bar Chart");

        jLabel58.setText("Bus Wise No. of Maintenances Comparision");

        jRadioButton98.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton98.setText("Bar Chart");

        jRadioButton99.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton99.setText("Pie Chart");

        jRadioButton89.setBackground(new java.awt.Color(0, 204, 153));
        jRadioButton89.setText("Pie Chart");
        jRadioButton89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton89ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jRadioButton88)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton89)
                                .addGap(249, 249, 249))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jSeparator44, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton90)
                            .addComponent(jLabel53)
                            .addComponent(jSeparator45, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(jLabel52))
                        .addGap(252, 252, 252))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jRadioButton98)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton99)))
                        .addContainerGap(429, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton88)
                    .addComponent(jRadioButton89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator44, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator45, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton98)
                    .addComponent(jRadioButton99))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transport", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jTextPane1.setText("                       Suggestion-Decision Graphical System");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        classWisePayments();
}//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
        classWisePayments();
}//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
        classWiseDues();
}//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
        classWiseDues();
}//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        classWiseNoOfStudents();
}//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        classWiseNoOfStudents();
}//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        CurrentSessionWiseNoOfEnquiriyByArea();
}//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        CurrentSessionWiseNoOfEnquiriyByArea();
}//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        AllSessionWiseNoOfEnquiriy();
}//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        CurrentSessionWiseNoOfEnquiriy();
}//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        CurrentSessionWiseNoOfEnquiriy();
}//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        ClassWiseCategory();
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
        ClassWiseGender();
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        ClassWiseReligion();
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
       classWiseFineNOtherDues();
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
        classWiseFineNOtherDues();
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
        classWiseFineNOtherPayments();
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
       classWiseFineNOtherPayments();
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton52ActionPerformed
         classWiseFineNOtherPayments();
    }//GEN-LAST:event_jRadioButton52ActionPerformed

    private void jRadioButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton53ActionPerformed
        classWiseFineNOtherPayments();
    }//GEN-LAST:event_jRadioButton53ActionPerformed

    private void jRadioButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton58ActionPerformed
        // TODO add your handling code here:
        VendorWiseNoOfDeals();
    }//GEN-LAST:event_jRadioButton58ActionPerformed

    private void jRadioButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton59ActionPerformed
        // TODO add your handling code here:
        VendorWiseNoOfDeals();
    }//GEN-LAST:event_jRadioButton59ActionPerformed

    private void jRadioButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton88ActionPerformed
       BusWiseNoOfStudents();
    }//GEN-LAST:event_jRadioButton88ActionPerformed

    private void jRadioButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton89ActionPerformed
      BusWiseNoOfStudents();
    }//GEN-LAST:event_jRadioButton89ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
ClassWiseNewAdmissions();        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButton8ActionPerformed


    public void classWiseNoOfStudents()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
            int stdclass;
            try
            {
                ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();


            while (rs.next())
            {
        stdclass=rs.getInt(2);
 ps = con.prepareStatement("select * from studententry where class=?");
 ps.setInt(1,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
j=0;
             System.out.println(r+""+r1);


            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton6.isSelected())
            barGraph(r,r1,"Class Wise Number of Students","Number Of Students","Class Title","Student_Strength_Bar");
            if(jRadioButton7.isSelected())
                pieGraph(r,r1,"Class Wise Number of Students","Student_Strength_Pie");
    }


    public void VendorWiseNoOfDeals()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
            int stdclass;
            try
            {
                ps = con.prepareStatement("select * from inventorysellersetup");

             rs = ps.executeQuery();


            while (rs.next())
            {
        stdclass=rs.getInt(3);
 ps = con.prepareStatement("select * from inventorydeposit where vendorname=?");
 ps.setInt(1,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(vendormap.get(rs.getInt(3)).toString());
             r1.add(j);
j=0;
             System.out.println(r+""+r1);


            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton58.isSelected())
            barGraph(r,r1,"Vendor Wise Number of Deals","Number Of Deals","Vendor Title","Vendor_Deal_Bar");
            if(jRadioButton59.isSelected())
                pieGraph(r,r1,"Vendor Wise Number of Deals","Vendor_Deal_Pie");
    }



public void CurrentSessionWiseNoOfEnquiriy()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
            int stdclass;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
 ps = con.prepareStatement("select * from admissionenquiry where session=? and class=?");
 ps.setInt(1,sessionValue);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
j=0;
             System.out.println(r+""+r1);


            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton1.isSelected())
          barGraph(r,r1,"Class Wise Enquiries","Number Of Enquiries","Class Name","Session_Enquiry_Bar");
            if(jRadioButton2.isSelected())
                pieGraph(r,r1,"Class Wise Number of Enquiries","Session_Enquiry_Pie");

    }

public void CurrentSessionWiseNoOfEnquiriyByArea()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
            String stdclass;
            try
            {
               ps = con.prepareStatement("select * from transportroutestopsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getString(2);
 ps = con.prepareStatement("select * from admissionenquiry where session=? and address=?");
 ps.setInt(1,sessionValue);
  ps.setString(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(rs.getString(2));
             r1.add(j);
j=0;
             System.out.println(r+""+r1);


            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton4.isSelected())
          barGraph(r,r1,"Area Wise Enquiries","Number Of Enquiries","Area Name","Session_Enquiry_Area_Bar");
            if(jRadioButton5.isSelected())
                pieGraph(r,r1,"Area Wise Number of Enquiries","Session_Enquiry_Area_Pie");

    }




        public void AllSessionWiseNoOfEnquiriy()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass,sess;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
        ps = con.prepareStatement("select * from sessionsetup");

             rs2 = ps.executeQuery();

           while (rs2.next())
            {
               sess=rs2.getInt(2);

 ps = con.prepareStatement("select * from admissionenquiry where session=? and class=?");
 ps.setInt(1,sess);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(sess);
j=0;
             System.out.println(r+""+r1);


            }
           }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
if(jRadioButton3.isSelected())
            barGraph1(r,r1,r2,"Class-Session Wise Admission Enquiry Comparision","Number of Enquiries","Class Name","Session_Enquiry_Comparision");
    }

         public void ClassWiseCategory()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass;
            String cat;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
        ps = con.prepareStatement("select * from categorysetup");

             rs2 = ps.executeQuery();

           while (rs2.next())
            {
               cat=rs2.getString(2);

 ps = con.prepareStatement("select * from studentdetail left join studententry on studententry.id=studentdetail.id where category=? and class=?");
 ps.setString(1,cat);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(cat);
j=0;
             System.out.println(r+""+r1+""+categorymap.get(cat));


            }
           }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
//if(jRadioButton3.isSelected())
  //          barGraph1(r,r1,r2,"Class-Session Wise Admission Enquiry Comparision","Number of Enquiries","Class Name","Session_Enquiry_Comparision");

if(jRadioButton13.isSelected())
            barGraph1(r,r1,r2,"Class-Category Wise Comparision","Number of Students","Class Name","Class_Category_Enquiry_Comparision");

         }


         public void ClassWiseNewAdmissions()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass;
            Date startdate,enddate;
            String sess;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
        ps = con.prepareStatement("select * from sessionsetup");

             rs2 = ps.executeQuery();

           while (rs2.next())
            {
              startdate=rs2.getDate(5);
             enddate=rs2.getDate(6);
         sess=rs2.getString(1);

 ps=con.prepareStatement("select * from studententry where doa >= ? and doa <= ? and class=?") ;
      ps.setDate(1, startdate);
      ps.setDate(2, enddate);
ps.setInt(3, stdclass);
             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(sess);
j=0;
            // System.out.println(r+""+r1+""+categorymap.get(cat));


            }
           }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
//if(jRadioButton3.isSelected())
  //          barGraph1(r,r1,r2,"Class-Session Wise Admission Enquiry Comparision","Number of Enquiries","Class Name","Session_Enquiry_Comparision");

if(jRadioButton8.isSelected())
            barGraph1(r,r1,r2,"Class-New Admissions Session-Wise Comparision","Number of Students","Class Name","Class_New_Admissions_Comparision");

         }


            public void BusWiseNoOfStudents()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
          String bus;
            try
            {
                ps = con.prepareStatement("select distinct busno from transportroutebussetup");

             rs = ps.executeQuery();


            while (rs.next())
            {
        bus=rs.getString(1);
 ps = con.prepareStatement("select * from transportboarders where busno=?");
 ps.setString(1,bus);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(bus);
             r1.add(j);
j=0;
             System.out.println(r+""+r1);


            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton88.isSelected())
            barGraph(r,r1,"Bus Wise Strength","Number Of Boarders","Bus No","Bus_Strength_Bar");
            if(jRadioButton89.isSelected())
                pieGraph(r,r1,"Bus Wise Strength","Bus_Strength_Pie");
    }


         public void ClassWiseReligion()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass;
            String cat;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
        ps = con.prepareStatement("select * from religionsetup");

             rs2 = ps.executeQuery();

           while (rs2.next())
            {
               cat=rs2.getString(2);

 ps = con.prepareStatement("select * from studentdetail left join studententry on studententry.id=studentdetail.id where religion=? and class=?");
 ps.setString(1,cat);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(cat);
j=0;
             System.out.println(r+""+r1+""+religionmap.get(cat));


            }
           }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
//if(jRadioButton3.isSelected())
  //          barGraph1(r,r1,r2,"Class-Session Wise Admission Enquiry Comparision","Number of Enquiries","Class Name","Session_Enquiry_Comparision");

if(jRadioButton16.isSelected())
            barGraph1(r,r1,r2,"Class-Religion Wise Comparision","Number of Students","Class Name","Class_Religion_Enquiry_Comparision");

         }



              public void ClassWiseGender()
    {
         int j = 0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass;
            String cat;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
       cat="M";
       for(int i=0;i<=1;i++)
       {


 ps = con.prepareStatement("select * from studententry where sex=? and class=?");
 ps.setString(1,cat);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j++;
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(cat);
j=0;
             System.out.println(r+""+r1);

cat="F";

           }
           }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
//if(jRadioButton3.isSelected())
  //          barGraph1(r,r1,r2,"Class-Session Wise Admission Enquiry Comparision","Number of Enquiries","Class Name","Session_Enquiry_Comparision");

if(jRadioButton13.isSelected())
            barGraph1(r,r1,r2,"Class-Category Wise Comparision","Number of Students","Class Name","Class_Category_Enquiry_Comparision");

            if(jRadioButton15.isSelected())
            barGraph1(r,r1,r2,"Class-Gender Wise Comparision","Number of Students","Class Name","Class_Gender_Enquiry_Comparision");

         }



            public void pieGraph(ArrayList r,ArrayList r1,String graphHead,String chartname)
    {
        try
            {
        DefaultPieDataset pieDataset = new DefaultPieDataset();
for(int i=0;i<r.size();i++)
        {
                pieDataset.setValue(r.get(i).toString(),Integer.parseInt(r1.get(i).toString()));
//pieDataset.setValue("Other", new Integer(25));
}
              JFreeChart chart = ChartFactory.createPieChart(graphHead,pieDataset,true,true,true);

               ChartUtilities.saveChartAsJPEG(new File("C:/Graphs/"+chartname+".jpg"),
                chart,1000, 500);
            //    writeChartToPDF(chart, 500, 400, "C://chart.pdf");
               } catch (Exception e) {
               System.out.println("Problem in creating chart.");
               }
               try {
            Runtime rt = Runtime.getRuntime();
           // rt.exec("SchoolPlus+_Help_File");
            Process pp=rt.exec(" rundll32 url.dll,FileProtocolHandler C:/Graphs/"+chartname+".jpg" );
// pp=rt.exec(" rundll32 url.dll,FileProtocolHandler C:/chart.pdf" );

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
public void barGraph(ArrayList r,ArrayList r1,String graphHead,String yaxis,String xaxis,String chartname)
{
    try
            {
        DefaultCategoryDataset pieDataset = new DefaultCategoryDataset();
        for(int i=0;i<r.size();i++)
        {
                   pieDataset.setValue(Integer.parseInt(r1.get(i).toString()),yaxis,r.get(i).toString());
        }

              JFreeChart chart =ChartFactory.createBarChart(graphHead,xaxis,yaxis,pieDataset, PlotOrientation.VERTICAL, true, true, true);

              final CategoryPlot plot = chart.getCategoryPlot();
 //       plot.setForegroundAlpha(0.5f);

              final CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
     // domainAxis.setLowerMargin(0.0);
       // domainAxis.setUpperMargin(0.0);
       
               ChartUtilities.saveChartAsJPEG(new File("C:/Graphs/"+chartname+".jpg"),
                chart,1000, 500);
               //writeChartToPDF(chart, 500, 400, "C://chart.pdf");
               } catch (Exception e) {
               System.out.println("Problem in creating chart.");
               }
               try {
            Runtime rt = Runtime.getRuntime();
           // rt.exec("SchoolPlus+_Help_File");
            Process pp=rt.exec(" rundll32 url.dll,FileProtocolHandler C:/Graphs/"+chartname+".jpg" );
           // pp=rt.exec(" rundll32 url.dll,FileProtocolHandler C:/chart.pdf" );


        } catch (Exception ex) {
            ex.printStackTrace();
        }
}


public void barGraph1(ArrayList r,ArrayList r1,ArrayList r2,String graphHead,String yaxis,String xaxis,String chartname)
{

    try
            {
        DefaultCategoryDataset pieDataset = new DefaultCategoryDataset();
        for(int i=0;i<r.size();i++)
        {
            if(jRadioButton3.isSelected())
                   pieDataset.setValue(Integer.parseInt(r1.get(i).toString()),sessionmap.get(Integer.parseInt(r2.get(i).toString())).toString(),r.get(i).toString());

        if(jRadioButton13.isSelected())
                   pieDataset.setValue(Integer.parseInt(r1.get(i).toString()),categorymap.get(r2.get(i)).toString(),r.get(i).toString());

            if(jRadioButton15.isSelected())
                   pieDataset.setValue(Integer.parseInt(r1.get(i).toString()),(r2.get(i)).toString(),r.get(i).toString());

                    if(jRadioButton16.isSelected())
                   pieDataset.setValue(Integer.parseInt(r1.get(i).toString()),religionmap.get(r2.get(i)).toString(),r.get(i).toString());
if(jRadioButton8.isSelected())
                   pieDataset.setValue(Integer.parseInt(r1.get(i).toString()),(r2.get(i)).toString(),r.get(i).toString());


        }
       JFreeChart chart =ChartFactory.createBarChart(graphHead,xaxis,yaxis,pieDataset, PlotOrientation.VERTICAL, true, true, true);

              CategoryPlot plot = chart.getCategoryPlot();
CategoryAxis domainAxis = plot.getDomainAxis();
domainAxis.setCategoryMargin(0.3f);
domainAxis.setLowerMargin(0.01d);
//plot.setBackgroundPaint(Color.cyan);
              //final CategoryPlot plot = chart.getCategoryPlot();
 //       plot.setForegroundAlpha(0.5f);

              //final CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
      //domainAxis.setLowerMargin(0.0);
        //domainAxis.setUpperMargin(0.0);



//domainAxis.DEFAULT_AXIS_MARGIN;
//domainAxis.setCategoryLabelPositionOffset(1);
//domainAxis.setCategoryMargin(WIDTH)

            /*  final CategoryAxis xAxis = new CategoryAxis("Type");
        xAxis.setLowerMargin(0.01d); // percentage of space before first bar
        xAxis.setUpperMargin(0.01d); // percentage of space after last bar
        xAxis.setCategoryMargin(0.25d); // percentage of space between categories
       */



          /*    CategoryPlot plot = chart.getCategoryPlot();

      // what can range axis do? maybe can delete this later
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();

      rangeAxis.setLowerMargin(0.1);
      rangeAxis.setUpperMargin(0.3);

      // set maximum width for bar
      final BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setMaximumBarWidth(0.06);*/

chart.setBackgroundPaint(Color.YELLOW);
               ChartUtilities.saveChartAsJPEG(new File("C:/Graphs/"+chartname+".jpg"),
                chart,1000, 500);
               } catch (Exception e) {
                   e.printStackTrace();
               System.out.println("Problem in creating chart.");
               }
               try {
            Runtime rt = Runtime.getRuntime();
           // rt.exec("SchoolPlus+_Help_File");
            Process pp=rt.exec(" rundll32 url.dll,FileProtocolHandler C:/Graphs/"+chartname+".jpg" );

        } catch (Exception ex) {
            ex.printStackTrace();
        }
}

  public void classWiseDues()
    {
         int j = 0;
         Double j1=0.0;
         Double j2=0.0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
            ArrayList r2 =new ArrayList();
            int stdclass;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
 ps = con.prepareStatement("select dues from feedues left join studententry on studentid=id where session=? and class=?");
 ps.setInt(1,sessionValue);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j+=rs1.getDouble(1);
    j1+=rs1.getDouble(1);
    j2+=rs1.getDouble(1);

}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(j2);
j=0;
j2=0.0;
             System.out.println(r+""+r1);
              System.out.println(r+""+r2);
System.out.println("Dues"+j1);

            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton18.isSelected())
            barGraph(r,r1,"Class Wise Dues for Current Session","Dues","Class Title","Class_Wise_Dues_Bar");
            if(jRadioButton19.isSelected())
                pieGraph(r,r1,"Class Wise Dues for Current Session","Class_Wise_Dues_Pie");

/* if(jRadioButton1.isSelected())
            barGraph1(r,r1);
            if(jRadioButton4.isSelected())
                pieGraph1(r,r1);
*/

         // Connection con;

      //  PreparedStatement ps;
          //  ResultSet rs,rs1;
    }

  public void classWisePayments()
    {
         int j = 0;
         Double j1=0.0;
         Double j2=0.0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
 ps = con.prepareStatement("select paid from feepaid left join studententry on studentid=id where session=? and class=?");
 ps.setInt(1,sessionValue);
  ps.setInt(2,stdclass);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j+=rs1.getDouble(1);
        j1+=rs1.getDouble(1);
         j2+=rs1.getDouble(1);
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(j2);
j=0;
j2=0.0;
             System.out.println(r+""+r1);
               System.out.println(r+""+r2);
System.out.println("payment"+j1);

            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton22.isSelected())
            barGraph(r,r1,"Class Wise Payment for Current Session","Payments","Class Title","Class_Wise_payments_Bar");
            if(jRadioButton21.isSelected())
                pieGraph(r,r1,"Class Wise Payment for Current Session","Class_Wise_Payments_Pie");


         // Connection con;

      //  PreparedStatement ps;
          //  ResultSet rs,rs1;
    }


  public void classWiseFineNOtherDues()
    {
         int j = 0;
         Double j1=0.0;
         Double j2=0.0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
            ArrayList r2 =new ArrayList();
            int stdclass;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
 ps = con.prepareStatement("select dues from feedues left join studententry on studentid=id where session=? and class=? and feetype=? and groupid=?");
 ps.setInt(1,sessionValue);
  ps.setInt(2,stdclass);
  ps.setInt(3,3);
  ps.setInt(4,0);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j+=rs1.getDouble(1);
    j1+=rs1.getDouble(1);
    j2+=rs1.getDouble(1);

}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(j2);
j=0;
j2=0.0;
             System.out.println(r+""+r1);
              System.out.println(r+""+r2);
System.out.println("Dues"+j1);

            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton24.isSelected())
            barGraph(r,r1,"Class Wise Fine & Other Dues","Dues","Class Title","Class_Wise_Other_Dues_Bar");
            if(jRadioButton25.isSelected())
                pieGraph(r,r1,"Class Wise Fine & Other Duesn","Class_Wise_Other_Dues_Pie");

/* if(jRadioButton1.isSelected())
            barGraph1(r,r1);
            if(jRadioButton4.isSelected())
                pieGraph1(r,r1);
*/

         // Connection con;

      //  PreparedStatement ps;
          //  ResultSet rs,rs1;
    }

  public void classWiseFineNOtherPayments()
    {
         int j = 0;
         Double j1=0.0;
         Double j2=0.0;
            ArrayList r =new ArrayList();
            ArrayList r1 =new ArrayList();
             ArrayList r2 =new ArrayList();
            int stdclass;
            try
            {
               ps = con.prepareStatement("select * from classsetup");

             rs = ps.executeQuery();

           while (rs.next())
            {
       stdclass=rs.getInt(2);
 ps = con.prepareStatement("select paid from feepaid left join studententry on studentid=id where session=? and class=? and feetype=? and groupid=?");
 ps.setInt(1,sessionValue);
  ps.setInt(2,stdclass);
ps.setInt(3,3);
if(jRadioButton26.isSelected() || jRadioButton27.isSelected())
  ps.setInt(4,0);
else
     ps.setInt(4,1);

             rs1 = ps.executeQuery();
while(rs1.next())
{
    j+=rs1.getDouble(1);
        j1+=rs1.getDouble(1);
         j2+=rs1.getDouble(1);
}
             r.add(classmap.get(rs.getInt(2)).toString());
             r1.add(j);
             r2.add(j2);
j=0;
j2=0.0;
             System.out.println(r+""+r1);
               System.out.println(r+""+r2);
System.out.println("payment"+j1);

            }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            if(jRadioButton27.isSelected())
            barGraph(r,r1,"Class Wise Fine & Other Payments","Payments","Class Title","Class_Wise_Other_Payments_Bar");
            if(jRadioButton26.isSelected())
                pieGraph(r,r1,"Class Wise Fine & Other Payments","Class_Wise_Other_Payments_Pie");

            if(jRadioButton52.isSelected())
            barGraph(r,r1,"Class Wise Inventory Payments","Payments","Class Title","Class_Wise_Inventory_Payments_Bar");
            if(jRadioButton53.isSelected())
                pieGraph(r,r1,"Class Wise Inventory Payments","Class_Wise_Inventory_Payments_Pie");


         // Connection con;

      //  PreparedStatement ps;
          //  ResultSet rs,rs1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton112;
    private javax.swing.JRadioButton jRadioButton113;
    private javax.swing.JRadioButton jRadioButton114;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton79;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton81;
    private javax.swing.JRadioButton jRadioButton82;
    private javax.swing.JRadioButton jRadioButton83;
    private javax.swing.JRadioButton jRadioButton84;
    private javax.swing.JRadioButton jRadioButton85;
    private javax.swing.JRadioButton jRadioButton88;
    private javax.swing.JRadioButton jRadioButton89;
    private javax.swing.JRadioButton jRadioButton90;
    private javax.swing.JRadioButton jRadioButton98;
    private javax.swing.JRadioButton jRadioButton99;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
ResultSet rs,rs1,rs2;
PreparedStatement ps;
public Integer sessionValue;
}
