/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * permanentDeleteOffRecords.java
 *
 * Created on Dec 1, 2009, 11:00:04 PM
 */

package com.duc.StudentDepartment.SearchStudent;

//import com.mysql.jdbc.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import static com.duc.DatabaseConnection.DatabaseConnection.*;

/**
 *
 * @author Ravi
 */
public class PermanentDeleteOffRecords extends javax.swing.JInternalFrame {

    /** Creates new form permanentDeleteOffRecords */
    public PermanentDeleteOffRecords() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        awardsentry = new javax.swing.JCheckBox();
        inventory = new javax.swing.JCheckBox();
        result = new javax.swing.JCheckBox();
        transport = new javax.swing.JCheckBox();
        surplus = new javax.swing.JCheckBox();
        waiver = new javax.swing.JCheckBox();
        removed = new javax.swing.JCheckBox();
        paid = new javax.swing.JCheckBox();
        dues = new javax.swing.JCheckBox();
        customize = new javax.swing.JCheckBox();
        group = new javax.swing.JCheckBox();
        attendance = new javax.swing.JCheckBox();
        library = new javax.swing.JCheckBox();
        letters = new javax.swing.JCheckBox();
        family = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Delete Records");

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextPane1.setText("                                                         Delete Selected Options");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane2.setEditable(false);
        jTextPane2.setText("On deleting Fee related options, you might not have a correct visualization of past Institute moneterial positions...Be careful...");
        jScrollPane2.setViewportView(jTextPane2);

        awardsentry.setBackground(new java.awt.Color(0, 204, 153));
        awardsentry.setText("Awards Entry Record");
        awardsentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awardsentryActionPerformed(evt);
            }
        });

        inventory.setBackground(new java.awt.Color(0, 204, 153));
        inventory.setText("Inventory Purchase Record");

        result.setBackground(new java.awt.Color(0, 204, 153));
        result.setText("Result Record");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        transport.setBackground(new java.awt.Color(0, 204, 153));
        transport.setText("Transport Record");
        transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportActionPerformed(evt);
            }
        });

        surplus.setBackground(new java.awt.Color(0, 204, 153));
        surplus.setText("Surplus Record");

        waiver.setBackground(new java.awt.Color(0, 204, 153));
        waiver.setText("Fee Waiver Record");

        removed.setBackground(new java.awt.Color(0, 204, 153));
        removed.setText("Fee Removed Record");
        removed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removedActionPerformed(evt);
            }
        });

        paid.setBackground(new java.awt.Color(0, 204, 153));
        paid.setText("Fee Paid Record");

        dues.setBackground(new java.awt.Color(0, 204, 153));
        dues.setText("Fee Dues Record");
        dues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duesActionPerformed(evt);
            }
        });

        customize.setBackground(new java.awt.Color(0, 204, 153));
        customize.setText("Customized Fee Record");

        group.setBackground(new java.awt.Color(0, 204, 153));
        group.setText("Student Group");
        group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupActionPerformed(evt);
            }
        });

        attendance.setBackground(new java.awt.Color(0, 204, 153));
        attendance.setText("Student Attendance Record");
        attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceActionPerformed(evt);
            }
        });

        library.setBackground(new java.awt.Color(0, 204, 153));
        library.setText("Student Library Record");

        letters.setBackground(new java.awt.Color(0, 204, 153));
        letters.setText("Issued Letters/Applications/Certificates");

        family.setBackground(new java.awt.Color(0, 204, 153));
        family.setText("Student Family Record");
        family.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyActionPerformed(evt);
            }
        });

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awardsentry)
                            .addComponent(letters)
                            .addComponent(inventory)
                            .addComponent(result)
                            .addComponent(library)
                            .addComponent(group)
                            .addComponent(attendance))
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transport)
                            .addComponent(surplus)
                            .addComponent(waiver)
                            .addComponent(removed)
                            .addComponent(paid)
                            .addComponent(dues)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customize)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(family)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customize)
                    .addComponent(awardsentry)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letters)
                    .addComponent(dues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventory)
                    .addComponent(paid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result)
                    .addComponent(removed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(library)
                    .addComponent(waiver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(group)
                    .addComponent(surplus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendance)
                    .addComponent(transport))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(family)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_transportActionPerformed

    private void attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_attendanceActionPerformed

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_groupActionPerformed

    private void awardsentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awardsentryActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_awardsentryActionPerformed

    private void duesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_duesActionPerformed

    private void removedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removedActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_removedActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_resultActionPerformed

    private void familyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_familyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       deleteSelectedData();
       jLabel1.setText("Selected Data Deleted");
    }//GEN-LAST:event_jButton1ActionPerformed

public void deleteSelectedData()
{
    //con=new com.duc.DatabaseConnection.DatabaseConnection().dataConnection();
    try
    {
        if(awardsentry.isSelected())
        {
            ps= con.prepareStatement("delete from awardsentry where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(letters.isSelected())
        {
            ps= con.prepareStatement("delete from issueletterhead where id=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(inventory.isSelected())
        {
            ps= con.prepareStatement("delete from studentinventorypurchase where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(result.isSelected())
        {
            ps= con.prepareStatement("delete from studentmarksentry where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(library.isSelected())
        {
            ps= con.prepareStatement("delete from studentlibraryrecord where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(group.isSelected())
        {
            ps= con.prepareStatement("delete from studentgroupmember where memberid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(attendance.isSelected())
        {
            ps= con.prepareStatement("delete from studentattendance where id_no=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(family.isSelected())
        {
            ps= con.prepareStatement("delete from studentfamily where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(customize.isSelected())
        {
            ps= con.prepareStatement("delete from feecustomization where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(dues.isSelected())
        {
            ps= con.prepareStatement("delete from feedues where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(paid.isSelected())
        {
            ps= con.prepareStatement("delete from feepaid where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(removed.isSelected())
        {
            ps= con.prepareStatement("delete from feeremoved where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(waiver.isSelected())
        {
            ps= con.prepareStatement("delete from feewaiver where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(surplus.isSelected())
        {
            ps= con.prepareStatement("delete from studentsurplus where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();

            ps= con.prepareStatement("delete from studentusedsurplus where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();

            ps= con.prepareStatement("delete from studenttodaysurplus where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }

        if(transport.isSelected())
        {
            ps= con.prepareStatement("delete from transportboarders where studentid=?");
            ps.setString(1, id);
            ps.executeUpdate();
        }



    }catch(Exception e)
    {
        e.printStackTrace();
    }
}

public void setFlag(int i)
{
    if(i==1)
    {
    inventory.setSelected(true);
    group.setSelected(true);
    attendance.setSelected(true);
    library.setSelected(true);
    family.setSelected(true);
    transport.setSelected(true);
    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox attendance;
    private javax.swing.JCheckBox awardsentry;
    private javax.swing.JCheckBox customize;
    private javax.swing.JCheckBox dues;
    private javax.swing.JCheckBox family;
    private javax.swing.JCheckBox group;
    private javax.swing.JCheckBox inventory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JCheckBox letters;
    private javax.swing.JCheckBox library;
    private javax.swing.JCheckBox paid;
    private javax.swing.JCheckBox removed;
    private javax.swing.JCheckBox result;
    private javax.swing.JCheckBox surplus;
    private javax.swing.JCheckBox transport;
    private javax.swing.JCheckBox waiver;
    // End of variables declaration//GEN-END:variables
//Connection con;
ResultSet rs;
PreparedStatement ps;
public String id=null;
}
